name: 'FOSSA'
description: 'Run FOSSA dependency analysis and upload'
inputs:
  version:
    description: "Specific version of fossa cli"
    required: false
runs:
  using: "composite"
  steps: 
    - run: bash ${{ github.action_path }}/github_actions/run.sh
      shell: bash
      env:
        FOSSA_CLI_VERSION: ${{ inputs.version }}

